### PR TITLE
Add support for running multiple plans to rhscl-postgresql-apb

### PR DESCRIPTION
**Pull request by jmontleon**

### CODE REVIEW

**Comment by jmontleon** [comment]
`
docker run -e "OPENSHIFT_TARGET=https://localhost:8443" -e "OPENSHIFT_USER=developer" -e "OPENSHIFT_PASS=developer"  testplans provision -e '{"namespace":"mwdev"}' -e '{"postgresql_password":"admin"}' -e '{"plan":"dev"}' -e '{"postgresql_database":"admin"}'
`

and

`
docker run -e "OPENSHIFT_TARGET=https://localhost:8443" -e "OPENSHIFT_USER=developer" -e "OPENSHIFT_PASS=developer"  testplans provision -e '{"namespace":"mwprod"}' -e '{"postgresql_password":"admin"}' -e '{"plan":"prod"}' -e '{"postgresql_database":"admin"}'
`

each give me the results I expect. The first produces one container with no pvc, and the second creates a container with a pvc for persistent storage.

I will look into whether it's reasonably possible to do an HA setup using the rhscl container(s)

**Comment by jmontleon** [comment]
@fabianvf @eriknelson @jmrodri @dymurray @cfchase - this is a first pass at an apb with support for running multiple plans. 

Probably of most interest is the new plan section in the apb.yml for the broker and apb. Please let me know if any changes are required.

**Comment by eriknelson** [comment]
Going to leave this open since I hope to have a broker able to deploy multiple plans in the next week or so. This APB may require some minor changes, but it's a great starting point for us on the broker side. Another APB with plans we hope to support soon is #79

**Comment by eriknelson** [comment]
Plan is to merge this, along with the other multi-plan related work into a feature branch so everything can be brought in atomically to master.

**Pull request merged**
