### PR TITLE
clean up titles in postgresql apb

### PR DESCRIPTION
**Pull request by jmontleon**

### CODE REVIEW

**Comment by tsanders-rh** [comment]
Jason - I am wondering if the title for namespace should be "Project".  I am thinking that is what it is called within the OpenShift UI.  Thoughts?

**Comment by rthallisey** [comment]
Kubernetes uses namespace and OpenShift uses project or namespace in the client. I think we should stay as close as we can to the syntax the larger community uses because it will make community adoption easier. I'm 👍 for keeping the namespace title.

**Comment by tsanders-rh** [comment]
We need to figure out how to handle upstream vs downstream.  As we found out this morning that the OpenShift UI is automatically adding an "Add to Project" attribute to the parameters section.  Which suggests we can drop this parameter from the apb.  However, I am not sure what happens in a kube environment.

**Comment by rthallisey** [comment]
Agreed about upstream vs downstream. I think this is tough because this work will be under the openshift umbrella and not kubernetes. But we want to have adoption from Kubernetes.

That's an interesting point about the UI. I think for using Kubernetes or Openshift without going through the UI you'll still need a param there.  I think we're going to need to sort out this downstream vs upstream sooner rather than later.

**Comment by fabianvf** [comment]
ACK

**Comment by tsanders-rh** [comment]
Agreed.  I want us to meet and discuss this.  Make some decisions.  I'll set something up.

**Pull request merged**
