### PR TITLE
update and clean up all examples

### PR DESCRIPTION
**Pull request by johnkim76**

### CODE REVIEW

**Review by rthallisey — APPROVED** [review]

**Comment by johnkim76** [comment]
[(5) Clean up fusor/apb-examples so all examples are up to date and working.](https://trello.com/c/lMzkf3CO/308-5-clean-up-fusor-apb-examples-so-all-examples-are-up-to-date-and-working)

**Comment by johnkim76** [comment]
@rthallisey I've made 2 more commits since your approval. Please re-review

**Comment by jmrodri** [comment]
I would've done the mass move as one PR. Then fixed them in another PR, for future big changes :)

**Comment by rthallisey** [comment]
Still LGTM

**Pull request merged**
